---
- name: Detecting - Inventory is available
  stat:
    path: '{{ inventory_path }}'
  register: inventory
- name: Getting current inventory state
  shell: 'test -f {{ inventory_path }} && cat {{ inventory_path }} || echo'
  register: inventory_state
  changed_when: False
  when:
    - inventory.stat.exists
- name: Applying defaults
  script: "{{ item }}"
  with_items:
    - "{{ lookup('fileglob', '*.defaults').split(',') }}"
  register: defaults
  notify:
    - Restart Finder
    - Restart Dock
    - Restart System UI Server
  when:
    - not inventory.stat.exists or lookup('file', item) | checksum not in inventory_state.stdout
- name: Creating inventory file
  file:
    path: '{{ inventory_path }}'
    state: touch
  when:
    - not inventory.stat.exists
    - defaults is succeeded
- name: Updating inventory with current state
  lineinfile:
    line: "{{ lookup('file', item) | checksum }}"
    dest: '{{ inventory_path }}'
    state: present
  with_items:
    - "{{ lookup('fileglob', '*.defaults').split(',') }}"
  when:
    - not inventory.stat.exists or lookup('file', item) | checksum not in inventory_state.stdout
