---
- name: Create secret variables
  blockinfile:
    marker: "# ANSIBLE MANAGED BLOCK - AWS"
    path: "{{home_directory}}/.bash_profile"
    block: "export AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}\n
            export AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}"
- name: Install awscli
  homebrew:
    name: awscli
